export default {
  chars: '总文字数',
  charsNoSpaces: '文字数 (无空格)',
  lines: '行数',
  output: '输出',
  encode: '编码',
  decode: '解码',
  data: '数据',
  showUnicodeChars: '显示 Unicode 字符',
  hideUnicodeChars: '隐藏 Unicode 字符',
  uppercaseBtn: '大小',
  lowercaseBtn: '小写',
  capitalizedBtn: '首字母大写',
  sentenceCaseBtn: '每句首字母大写',
  HTMLDataEncoderDecoder: 'HTML 数据编码/解码',
  XMLDataEncoderDecoder: 'XML 数据编码/解码',
  URLDataEncoderDecoder: 'URL 数据编码/解码',
  URLUnicodeTransformer: '显示/隐藏 URL 中的 Unicode 字符',
  CaseConverter: '大小写转换器',
  copy: '复制',
  copied: '复制成功',
  copyNotSupported: '您的浏览器不支持自动复制，请手动复制。',
  CharacterLineCounter: '字数/行数统计',
  toolset: '工具箱',
  feedback: '反馈问题',
  signIn: '登录',
  ColorPickerConverter: '颜色选择器/转换器',
  prettify: '格式化/美化',
  JavaScriptFormatter: 'JavaScript 格式化/美化',
  options: '选项',
  docs: '文档',
  reset: '重置',
  errorTitle: '错误',
  invalidOptsJSON: '选项不是正确的JSON',
  TypeScriptFormatter: 'TypeScript 格式化/美化',
  CSSFormatter: 'CSS 格式化/美化',
  MarkdownFormatter: 'Markdown 格式化/美化',
  JSONFormatter: 'JSON 格式化/美化',
  DecodeUnicodeJSON: '解码 JSON 中的 Unicode (UTF-16)',
  examples: '示例',
};
