window.cft_ls = {
  chars: 'Characters',
  charsNoSpaces: 'Characters (no spaces)',
  lines: 'Lines',
  output: 'Output',
  encode: 'Encode',
  decode: 'Decode',
  data: 'Data',
  showUnicodeChars: 'Show Unicode Characters',
  hideUnicodeChars: 'Hide Unicode Characters',
  uppercaseBtn: 'UPPERCASE',
  lowercaseBtn: 'lowercase',
  capitalizedBtn: 'Capitalized Case',
  sentenceCaseBtn: 'Sentence Case',
  HTMLDataEncoderDecoder: 'HTML Data Encoder/Decoder',
  XMLDataEncoderDecoder: 'XML Data Encoder/Decoder',
  URLDataEncoderDecoder: 'URL Data Encoder/Decoder',
  URLUnicodeTransformer: 'Show/Hide URL Unicode Characters',
  CaseConverter: 'Case Converter',
  copy: 'Copy',
  copied: 'Copied',
  copyNotSupported:
    'Your browser does not support copy API, please copy manually.',
  CharacterLineCounter: 'Character/Line Counter',
  toolset: 'ToolSet',
  feedback: 'Feedback',
  signIn: 'Sign In',
  ColorPickerConverter: 'Color Picker/Converter (RGBA/HSLA)',
  prettify: 'Format/Prettify',
  JavaScriptFormatter: 'JavaScript Formatter/Prettifier',
  options: 'Options',
  docs: 'Docs',
  reset: 'Reset',
  errorTitle: 'Oops!',
  invalidOptsJSON: 'Invalid options JSON value',
  TypeScriptFormatter: 'TypeScript Formatter/Prettifier',
  CSSFormatter: 'CSS Formatter/Prettifier',
  MarkdownFormatter: 'Markdown Formatter/Prettifier',
  JSONFormatter: 'JSON Formatter/Prettifier',
  DecodeUnicodeJSON: 'Decode Unicode (UTF-16) in JSON',
  examples: 'Examples',
  JavaScriptExportAllNamedImports: 'JavaScript export all named imports',
  extract: 'Extract',
  JSONMinifier: 'JSON Minifier',
  minify: 'Minify',
  grayscale: 'Grayscale',
};
