module.exports = {
  chars: 'Characters',
  charsNoSpaces: 'Characters (no spaces)',
  lines: 'Lines',
  output: 'Output',
  encode: 'Encode',
  decode: 'Decode',
  data: 'Data',
  showUnicodeChars: 'Show unicode chars',
  hideUnicodeChars: 'Hide unicode chars',
  uppercaseBtn: 'UPPERCASE',
  lowercaseBtn: 'lowercase',
  capitalizedBtn: 'Capitalized Case',
  sentenceCaseBtn: 'Sentence Case',
  HTMLDataEncoderDecoder: 'HTML Data Encoder/Decoder',
  XMLDataEncoderDecoder: 'XML Data Encoder/Decoder',
  URLDataEncoderDecoder: 'URL Data Encoder/Decoder',
  URLUnicodeTransformer: 'Show/Hide URL Unicode Chars',
  CaseConverter: 'Case Converter',
};
